# Generated by Django 5.0.6 on 2024-06-24 06:51

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0001_initial"),
        ("hosts", "0001_initial"),
        ("shows", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", autoslug.fields.AutoSlugField(unique=True)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("video_id", models.CharField(max_length=11, unique=True)),
                ("link", models.URLField(blank=True, max_length=43)),
                (
                    "blurb",
                    models.TextField(
                        blank=True,
                        help_text="Video description",
                        verbose_name="Blurb",
                    ),
                ),
                (
                    "audio_only",
                    models.ManyToManyField(
                        blank=True,
                        related_name="audio_only_in_videos",
                        related_query_name="video_audio_only",
                        to="hosts.host",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        related_query_name="video_channel",
                        to="channels.channel",
                    ),
                ),
                (
                    "guests",
                    models.ManyToManyField(
                        blank=True,
                        related_name="guest_in_videos",
                        related_query_name="video_guest",
                        to="hosts.host",
                    ),
                ),
                (
                    "hosts",
                    models.ManyToManyField(
                        blank=True,
                        related_name="hosted_videos",
                        related_query_name="video_host",
                        to="hosts.host",
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"kf_crew": True},
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produced_videos",
                        related_query_name="video_producer",
                        to="hosts.host",
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        related_query_name="video_show",
                        to="shows.show",
                    ),
                ),
            ],
        ),
    ]
