# Generated by Django 5.0.6 on 2024-07-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0002_remove_video_audio_only_remove_video_guests"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="link",
            field=models.URLField(blank=True),
        ),
    ]
