# Generated by Django 5.0.6 on 2024-07-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("videos", "0003_alter_video_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="slug",
        ),
        migrations.AlterField(
            model_name="video",
            name="blurb",
            field=models.TextField(
                blank=True,
                help_text="Video description pulled from the YouTube API. Empty if Patreon.",
                verbose_name="Blurb",
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="release_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
