repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-ast
    -   id: check-yaml
    -   id: check-toml
    -   id: check-docstring-first
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
    -   id: black
