# Generated by Django 5.0.6 on 2024-06-12 04:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("channels", "0001_initial"),
        ("hosts", "0001_initial"),
        ("shows", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("release_date", models.DateField(blank=True, null=True)),
                ("video_id", models.CharField(max_length=11, unique=True)),
                ("link", models.URLField(blank=True, max_length=43)),
                (
                    "blurb",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the episode.",
                        null=True,
                        verbose_name="Blurb",
                    ),
                ),
                (
                    "short",
                    models.BooleanField(
                        default=False, verbose_name="YouTube Short"
                    ),
                ),
                (
                    "members_only",
                    models.BooleanField(
                        default=False,
                        help_text="The episode is only available for YouTube/Patreon members.",
                    ),
                ),
                (
                    "channel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        related_query_name="episode_channel",
                        to="channels.channel",
                    ),
                ),
                (
                    "guests",
                    models.ManyToManyField(
                        related_name="guest_in_episodes",
                        related_query_name="episode_guest",
                        to="hosts.host",
                    ),
                ),
                (
                    "hosts",
                    models.ManyToManyField(
                        related_name="hosted_episodes",
                        related_query_name="episode_host",
                        to="hosts.host",
                    ),
                ),
                (
                    "producer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produced_episodes",
                        related_query_name="episode_producer",
                        to="hosts.host",
                    ),
                ),
                (
                    "show",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="episodes",
                        related_query_name="episode_show",
                        to="shows.show",
                    ),
                ),
            ],
        ),
    ]
