# Generated by Django 5.0.6 on 2024-06-12 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("episodes", "0001_initial"),
        ("hosts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="episode",
            name="guests",
            field=models.ManyToManyField(
                limit_choices_to={"kf_crew": False, "part_timer": False},
                related_name="guest_in_episodes",
                related_query_name="episode_guest",
                to="hosts.host",
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="hosts",
            field=models.ManyToManyField(
                limit_choices_to=models.Q(
                    ("kf_crew", True), ("part_timer", True), _connector="OR"
                ),
                related_name="hosted_episodes",
                related_query_name="episode_host",
                to="hosts.host",
            ),
        ),
        migrations.AlterField(
            model_name="episode",
            name="producer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"kf_crew": True},
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="produced_episodes",
                related_query_name="episode_producer",
                to="hosts.host",
            ),
        ),
    ]
