# Generated by Django 5.0.6 on 2024-06-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="host",
            index=models.Index(
                fields=["kf_crew", "part_timer"], name="crew_pt_idx"
            ),
        ),
    ]
