# Generated by Django 5.0.6 on 2024-07-01 02:56

import apps.hosts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0002_host_crew_pt_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="image_xs",
            field=models.ImageField(
                blank=True, upload_to=apps.hosts.models.slug_directory_path
            ),
        ),
    ]
