# Generated by Django 5.0.6 on 2024-07-18 00:14

import apps.hosts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0003_host_image_xs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="640x640 webp",
                upload_to=apps.hosts.models.slug_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="image_xs",
            field=models.ImageField(
                blank=True,
                help_text="96x96 webp",
                upload_to=apps.hosts.models.slug_directory_path,
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="nicknames",
            field=models.JSONField(
                blank=True,
                help_text="Should be formatted as a list.",
                null=True,
                verbose_name="Nickname(s)",
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="slug",
            field=models.SlugField(
                help_text="URL-compatible host name.", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="host",
            name="socials",
            field=models.JSONField(
                blank=True,
                help_text="Should be formatted as a dictionary.",
                null=True,
            ),
        ),
    ]
