# Generated by Django 5.0.6 on 2024-07-18 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0002_channel_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="blurb",
            field=models.TextField(
                blank=True, help_text="Optional description of the channel."
            ),
        ),
        migrations.AlterField(
            model_name="channel",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
