# Generated by Django 5.0.6 on 2024-06-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "active",
                    models.BooleanField(
                        default=False, verbose_name="Is Active"
                    ),
                ),
                (
                    "blurb",
                    models.TextField(
                        blank=True,
                        help_text="Optional description of the show.",
                        null=True,
                    ),
                ),
            ],
        ),
    ]
