# Generated by Django 5.0.6 on 2024-06-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="active",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="Is Active"
            ),
        ),
        migrations.AlterField(
            model_name="show",
            name="slug",
            field=models.SlugField(db_index=False, unique=True),
        ),
        migrations.AddIndex(
            model_name="show",
            index=models.Index(
                fields=["slug", "name"], name="show_slug_name_idx"
            ),
        ),
    ]
