# Generated by Django 5.0.6 on 2024-07-01 05:09

import apps.shows.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shows", "0002_alter_show_active_alter_show_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="image_xs",
            field=models.ImageField(
                blank=True, upload_to=apps.shows.models.slug_directory_path
            ),
        ),
    ]
