# Generated by Django 5.0.6 on 2024-07-09 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0001_initial"),
        ("shows", "0003_show_image_xs"),
    ]

    operations = [
        migrations.AddField(
            model_name="show",
            name="channels",
            field=models.ManyToManyField(
                blank=True,
                related_name="channel_videos",
                related_query_name="show_channel",
                to="channels.channel",
            ),
        ),
    ]
