# Generated by Django 5.0.6 on 2024-07-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0001_initial"),
        ("shows", "0004_show_channels"),
    ]

    operations = [
        migrations.AlterField(
            model_name="show",
            name="channels",
            field=models.ManyToManyField(
                blank=True,
                related_name="channel_shows",
                related_query_name="show_channel",
                to="channels.channel",
            ),
        ),
    ]
