# Generated by Django 5.0.6 on 2024-07-18 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("edits", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="channeledit",
            old_name="video",
            new_name="channel",
        ),
        migrations.RenameField(
            model_name="hostedit",
            old_name="video",
            new_name="host",
        ),
        migrations.RenameField(
            model_name="showedit",
            old_name="video",
            new_name="show",
        ),
    ]
