# Generated by Django 5.0.6 on 2024-07-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("edits", "0002_rename_video_channeledit_channel_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="channeledit",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("VWD", "Viewed"),
                    ("WIP", "In Progress"),
                    ("CPL", "Complete"),
                    ("CNC", "Cancelled"),
                    ("SPM", "Spam"),
                ],
                default="New",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="hostedit",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("VWD", "Viewed"),
                    ("WIP", "In Progress"),
                    ("CPL", "Complete"),
                    ("CNC", "Cancelled"),
                    ("SPM", "Spam"),
                ],
                default="New",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="showedit",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("VWD", "Viewed"),
                    ("WIP", "In Progress"),
                    ("CPL", "Complete"),
                    ("CNC", "Cancelled"),
                    ("SPM", "Spam"),
                ],
                default="New",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="videoedit",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("VWD", "Viewed"),
                    ("WIP", "In Progress"),
                    ("CPL", "Complete"),
                    ("CNC", "Cancelled"),
                    ("SPM", "Spam"),
                ],
                default="New",
                max_length=32,
            ),
        ),
    ]
