# Generated by Django 5.0.6 on 2024-07-18 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "edits",
            "0003_channeledit_status_hostedit_status_showedit_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="channeledit",
            options={},
        ),
        migrations.AlterModelOptions(
            name="hostedit",
            options={},
        ),
        migrations.AlterModelOptions(
            name="showedit",
            options={},
        ),
        migrations.AlterModelOptions(
            name="videoedit",
            options={},
        ),
    ]
