# Generated by Django 5.0.6 on 2024-07-18 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "edits",
            "0004_alter_channeledit_options_alter_hostedit_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="channeledit",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("VWD", "Viewed"),
                    ("WIP", "In Progress"),
                    ("CPL", "Complete"),
                    ("CNC", "Cancelled"),
                    ("SPM", "Spam"),
                ],
                default="NEW",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="hostedit",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("VWD", "Viewed"),
                    ("WIP", "In Progress"),
                    ("CPL", "Complete"),
                    ("CNC", "Cancelled"),
                    ("SPM", "Spam"),
                ],
                default="NEW",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="showedit",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("VWD", "Viewed"),
                    ("WIP", "In Progress"),
                    ("CPL", "Complete"),
                    ("CNC", "Cancelled"),
                    ("SPM", "Spam"),
                ],
                default="NEW",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="videoedit",
            name="status",
            field=models.CharField(
                choices=[
                    ("NEW", "New"),
                    ("VWD", "Viewed"),
                    ("WIP", "In Progress"),
                    ("CPL", "Complete"),
                    ("CNC", "Cancelled"),
                    ("SPM", "Spam"),
                ],
                default="NEW",
                max_length=32,
            ),
        ),
    ]
