# Generated by Django 5.0.6 on 2024-07-18 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "edits",
            "0005_alter_channeledit_status_alter_hostedit_status_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="channeledit",
            name="topic",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="hostedit",
            name="topic",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="showedit",
            name="topic",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="videoedit",
            name="topic",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
