name: Continuous Integration Checks

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    name: Unit tests and code checks
    runs-on: ubuntu-latest
    env:
      REDIS_HOST: ${{ secrets.REDIS_HOST }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      REDIS_PW: ${{ secrets.REDIS_PW }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install CI
        run: |
          if [[ -z "$REDIS_HOST" || -z "$REDIS_PORT" || -z "$REDIS_PW" ]]; then
            echo "Error: One or more environment variables missing."
            exit 1
          fi
          pip install "tox>=4.0"
          tox
