name: Continuous Integration Checks

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:

    name: Unit tests and code checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Set environment variables and install CI
        env:
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_PW: ${{ secrets.REDIS_PW }}
        run: |
            pip install "tox>=4.0"
            tox
